# It will check whether if anyone tries to change the code, LINTER will autmatically check the code, syntax, indendation is correct or not

name: Auto Linter
on:
  push: 
    paths: "*.py"
  
jobs:
  Code_Linter:
    runs-on: ubuntu-latest
    steps:
        # This will automatically clone the code of current branch into the runner 
      - name: Clone/Checkout the code
        uses: actions/checkout@v7 
        # This step will install python with version 3.12
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
        # This will install the linting tool
      - name: Install linter package
        run: pip install ruff
        # This will run the linter
      - name: check the files for linting
        run: ruff check .
    
  
